import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Loader</Link>
        </li>
        <li>
          <Link to="/loginlight">Loginlight</Link>
        </li>
        <li>
          <Link to="/registerlight">Registerlight</Link>
        </li>
        <li>
          <Link to="/bmi">BMI</Link>
        </li>
        <li>
          <Link to="/landingnew">LandingNew</Link>
        </li>
        <li>
          <Link to="/mainpageone">MainPageOne</Link>
        </li>
        <li>
          <Link to="/mainpagefive">MainPageFive</Link>
        </li>
        <li>
          <Link to="/mainpagesix">MainPageSix</Link>
        </li>
        <li>
          <Link to="/mainpage">MainPage</Link>
        </li>
        <li>
          <Link to="/mainpagenine">MainPageNine</Link>
        </li>
        <li>
          <Link to="/mainpagethree">MainPageThree</Link>
        </li>
        <li>
          <Link to="/mainpagetwo">MainPageTwo</Link>
        </li>
        <li>
          <Link to="/mainpageeight">MainPageEight</Link>
        </li>
        <li>
          <Link to="/mainpageten">MainPageTen</Link>
        </li>
        <li>
          <Link to="/mainpagefour">MainPageFour</Link>
        </li>
        <li>
          <Link to="/mainpageseven">MainPageSeven</Link>
        </li>
        <li>
          <Link to="/mainpagethirteen">MainPageThirteen</Link>
        </li>
        <li>
          <Link to="/mainpagetwelve">MainPageTwelve</Link>
        </li>
        <li>
          <Link to="/mainpageeleven">MainPageEleven</Link>
        </li>
        <li>
          <Link to="/typography">Typography</Link>
        </li>
        <li>
          <Link to="/components">Components</Link>
        </li>
        <li>
          <Link to="/frametwo">FrameTwo</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
